### ISSUE TITLE
定期的に「java.io.IOException: 存在しないデバイスを指定しました。」が発生する

### ISSUE THREAD

**Issue by genhirano** [genhirano/Last-Appearance-in-PI#41]
定期的に「java.io.IOException: 存在しないデバイスを指定しました。」が発生する

これが発生するたびにそのユニットを最初からやりなおしているが、何度もやりなおしているため改善したい

```
 592| 591 590 589 588| 587 586 585 584 583 582| 581 580 579 578 577| 576 575 574 573| 572 571 570 569 568 567 566| 565 564| 563 562 561 560| 559 558| 557 556 555| 554 553 552 551 550 549| 548 547 546 545 544| 543 542 541| 540| 539 538 537 536 535| 534 533 532 531 530| 529 528 527| 526 525 524| 523 522 521 520| 519 518 517 516| 515 514 513 512 511| 510 509 508 507 506| 505 504 503 502 501| 500 499 498 497 496 495java.lang.RuntimeException: ERROR!  start over. count: 1
        at controller.Searcher.survive(Searcher.java:209)
        at controller.Searcher.run(Searcher.java:90)
Caused by: java.lang.RuntimeException: YCD Data read error. H:\Pi\Pi - Dec - Chudnovsky - 0.ycd
        at model.ycd.YCD_SeqProvider.next(YCD_SeqProvider.java:154)
        at model.ycd.YCD_SeqProvider.next(YCD_SeqProvider.java:1)
        at controller.Searcher.survive(Searcher.java:163)
        ... 1 more
Caused by: java.io.IOException: 存在しないデバイスを指定しました。
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
        at model.ycd.YCD_SeqBlockStream.nextBlockRead(YCD_SeqBlockStream.java:303)
        at model.ycd.YCD_SeqBlockStream.next(YCD_SeqBlockStream.java:224)
        at model.ycd.YCD_SeqProvider.next(YCD_SeqProvider.java:123)
        ... 3 more
```

**Comment by genhirano** [comment]
#46 で対応済み。
